### ISSUE TITLE
Fresh install - ERROR  There are no commands defined in the "livewire" namespace.

### ISSUE THREAD

**Issue by johanguse** [electrikhq/electrik#29]
Hello! I followed the instructions provided in the readme file and encountered an error with Livewire before the command `php artisan electrik:install  `

![image](https://github.com/electrikhq/electrik/assets/6184866/0e4c13d5-ec0b-46cc-8635-5440cf9e0baf)

**Comment by neerajsohal** [comment]
Hey,

Sorry to hear that you're facing installation issues. Can you share the list of commands you ran to install Electrik. Right from the beginning?

It'll help me in investigating the issue better.

Best,
Neeraj.

**Comment by neerajsohal** [comment]
Also, please confirm the Laravel version you are using.

**Comment by johanguse** [comment]
I am running exactly the same commands from ReadMe file on PHP 8.1.13

Create a fresh laravel application
`composer create-project laravel/laravel projectx --prefer-dist`

Move to project folder
`cd projectx`

Requiire Electrik via composer
`composer require electrik/electrik`

Install Electrik
`php artisan electrik:install` <- the error happen here!

This is my composer.json

```
"require": {
        "php": "^8.1",
        "electrik/electrik": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "*"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
```

![image](https://github.com/electrikhq/electrik/assets/6184866/9c8ef19c-9edc-4423-9982-fc803e97ae0e)

**Comment by johanguse** [comment]
In case you need my composer version and PHP version used on my terminal.

PHP 8.2.4 (cli)
Composer version 2.5.4

**Comment by neerajsohal** [comment]
Thanks a lot for taking out time and sharing a detailed description of the issue. 

I have found the issue. The current branch 2.x is not stable. It's still under development for supporting Laravel 10.x 

The errors are coming because of the dependencies not supporting L10.x. For e.g. teamwork package still only supports 9.x. 

I can give you two options here:

1. Either use L9.x and try installing Electrik's [0.0.13](https://github.com/electrikhq/electrik/tree/0.0.13) version.
2. Wait for a few days till the time dependencies start supporting 10.x completely.

In either case, I am updating the README to highlight this issue. And I'll myself submit PRs to the packages still not supporting 10.x

Best,
Neeraj.

**Comment by neerajsohal** [comment]
There is an open issue regarding this. You can subscribe to it to keep a track on what's the status: #25

**Comment by johanguse** [comment]
Ok, I'll follow issue #25. Thank you!
